image: matsubara0507/stack-build
output: "."
template:
  before_env: "Dockerfile.template.1"
  after_env: "Dockerfile.template.2"
base:
  repo: ubuntu
  tag: "18.04"
env:
  stack_version:
    github:
      repo: commercialhaskell/stack
      hook: release
      strip_prefix: v
tags:
- type: value
  keys:
  - latest
  always: true
- type: refer
  ref: https://www.stackage.org/download/snapshots.json
  keys:
  - nightly
  - lts
  - lts-14
  - lts-13
  - lts-12
