output: "."
template:
  before_env: "Dockerfile.template.1"
  after_env: "Dockerfile.template.2"
base:
  repo: ubuntu
  tag: "18.04"
env:
  stack_version:
    github:
      repo: commercialhaskell/stack
      hook: release
      strip_prefix: v
