name:                dockwright
version:             0.1.0.0
github:              "matsubara0507/dockwright"
license:             MIT
author:              "MATSUBARA Nobutada"
maintainer:          "t12307043@gunma-u.ac.jp"
copyright:           "2018 MATSUBARA Nobutada"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/matsubara0507/dockwright#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- NoImplicitPrelude

- ConstraintKinds
- FlexibleContexts
- FlexibleInstances
- OverloadedStrings
- PolyKinds
- TypeFamilies
- TypeSynonymInstances

dependencies:
- base >= 4.7 && < 5
- rio >= 0.1.1.0
- extensible >= 0.6
- language-docker
- req >= 2.0
- yaml

library:
  source-dirs: src

executables:
  dockwright:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - dockwright
    - githash

tests:
  dockwright-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - dockwright
    - tasty
    - tasty-hspec
