resolver: lts-17.4
packages:
- .
extra-deps:
- dockerfile-creator-0.1.0.0
- extensible-0.8.1
- fallible-0.1.0
- incremental-0.3.1
- membership-0
- github: matsubara0507/mix.hs
  commit: 75714be080db16f6a4f9d0a22e86947ffcdadc57
  subdirs:
  - mix
  - mix-json-logger

docker:
  repo: ghcr.io/matsubara0507/stack-build:18.04
  enable: false
