resolver: lts-14.4
packages:
- .
extra-deps:
- extensible-0.6.1
- membership-0
- github: matsubara0507/fallible
  commit: dfbdce1a0b0c71bcfcea844c94f9cb815f071235
- github: matsubara0507/mix.hs
  commit: c6c303f9ddf4655a42804ee67d512af6d3b14e98
  subdirs:
  - mix
  - mix-json-logger

docker:
  repo: matsubara0507/stack-build
  enable: false
